### ISSUE TITLE
when to support export mobi

### ISSUE THREAD

**Issue by tttMelody** [alexadam/save-as-ebook#5]
thanks a lot.And i have another question that the table in the context can not been seen(i mean the cell not the content)
![image](https://cloud.githubusercontent.com/assets/15643702/20514465/01f40a40-b0c7-11e6-85e8-ac0754cb6e0c.png)

and it should be:
![image](https://cloud.githubusercontent.com/assets/15643702/20514492/1dc819e6-b0c7-11e6-84d7-1c53234c6dec.png)
and can this plugin support to convert .md to .epub?

thanks again

**Comment by alexadam** [comment]
I think the table issue is because it doesn't support css styles. Implementing it is on the top of my list but I didn't find a simple way to integrate with the current UI.
As far as I know .mobi is a proprietary format and I cannot add it without a license (?) but I will consider support for other formats after I add styles. I will keep you updated.

**Comment by tttMelody** [comment]
thank you for your response~
